### PR TITLE
Adding DNS records section

### PR DESCRIPTION
**Pull request by shilch**

### CODE REVIEW

**Comment by shilch** [comment]
Well, you need DNS either way: the client has to know which server to contact for a specific domain.  
So why not allowing the CCAP service to be hosted under a different server? This would allow you to let 3rd party servers to handle your domain.

**Comment by FrilledShark** [comment]
Yeah and incase you need to configure anything other than a A record, it would have been fair easier to just go with https://openalias.org. It is already developed, implemented and used.

If you want to use another server than self hosted, one should look at the proposal desrt made in the Discord server:

> @lane.c.wagner had a look at your ccap project. at it current implementation it would always query the main domain right?
so if I want $desrt.nanonode.ninja it would query https://nanonode.ninja/ccap/address/desrt/NANO ?
I would suggest adding a different subdomain for that because now I would have to implement all the ccap logic into my main project (or struggle with some nasty nginx backends for specific subfolders)
so ideally it would query ccap.nanonode.ninja with all the rest where I would simply setup the server for all that

**Comment by shilch** [comment]
A large host might want to run multiple servers with different priorities and weight which is exactly what SRV records were created for. I believe that almost all domain sellers allow SRV entries to be created on their name servers as these records are used quite often. We can also make SRV optional and fall back to A or CNAME records.  

Regarding OpenAlias: This project does only map domain -> address via DNS, right? This is a good choice for open-source projects that have a fixed donation address but does not work well with many users and ever changing entries.

**Comment by shilch** [comment]
Same as you can let Gmail handle mails to your domain.  
There are not even security issues as you could specify a public key in a TXT entry of your domain that all addresses sent from the CCAP server have to be signed with.

**Comment by lane-c-wagner** [comment]
@shilch Is there a way we can do it so that the record isn't REQUIRED but is available. For instance, my alias is lane@ogdolo.com... The wallet wishing to send me money checks ogdolo.com for any SRV records. If there IS one then it will use that record to forward to the hosting server. If there ISN'T one, then it will just use ogdolo.com.

I think that may satisfy @FrilledShark ? That way we get best of both worlds.

**Comment by shilch** [comment]
@lane-c-wagner That's exactly what I meant. We'll need to specify a standard port then.

**Comment by FrilledShark** [comment]
No, what I mean is: https://openalias.org is already the proposed way to create aliases. Monero and Bitcoin already uses it.

Why do we need an additional alias system?

**Comment by shilch** [comment]
OpenAlias is completely DNS based. As I said, this is a good choice for open-source projects that have a fixed donation address but does not work well with many users and ever changing entries.

**Comment by FrilledShark** [comment]
@shilch Why?

**Comment by FrilledShark** [comment]
Well, if we are talking about adding DNS records beyond just A, you would have to take all precautions that OpenAlias takes.

We would arrive at the wallets having to use DNScrypt nameservers (for privacy), verify DNSSEC (To know TXT and SRV are authentic), verify certificate of domain and send a get request to the endpoint.

**Comment by FrilledShark** [comment]
Unless I am mistaken, both of the below SRV record are valid.
`_ccap._tcp.ogdolo.com. 3600 IN SRV 10 0 1337 ccap01.ogdolo.com.`
`_ccap._tcp.ogdolo.com. 3600 IN SRV 10 0 1337 ccap01.legitdomain.com.`

Therefore, I could (as the evil guy) give the dns record a round of poison and turn your SRV record into mine and the GET requests would arrive at my servers instead of yours.

**Comment by shilch** [comment]
The point of SRV is that you can load balance requests. You as the evil guy can not simply change DNS entries. You would need access to the domain on the left side of the entry.  
If this kind of attack worked you could do the same thing with A records.

**Comment by FrilledShark** [comment]
https://openalias.org/#implement (Notice DNSSEC is required)

Yes, it is possible. See my edit for A records.
https://en.wikipedia.org/wiki/DNS_spoofing
https://www.howtogeek.com/161808/htg-explains-what-is-dns-cache-poisoning/
https://www.networkworld.com/article/2277316/tech-primers/tech-primers-how-dns-cache-poisoning-works.html
https://www.calyptix.com/top-threats/3-common-dns-attacks-and-how-to-fight-them/

**Comment by shilch** [comment]
I don't know how DNS security works in detail, but where is the difference in attacking an A vs. an SRV record?

**Comment by FrilledShark** [comment]
The A record is protected by only using HTTPS  for GET and POST requests and verifying the certificate. This is because when you get the certificate for the domain, the certificate issuer verifies that everything is correct and you are visiting the correct site.  This is part of the reason why not everyone can issue valid certificates.

SRV is not protected. The only way to know that the issuer created that exact SRV record is DNSSEC. Because it is a very niche attack, it is usually not to be worried about, however it is an open attack vector which can be used to provide an incorrect address and therefore steal money.

This is why when OpenAlias uses TXT record, DNSSEC is **always required**, with no exception. Without DNSSEC, you have no way of knowing where the TXT record came from.

**Comment by BitDesert** [comment]
My initial idea at Discord (DESRT#0337) was an OpenAlias type of system too, but that changed when I thought about the developer side... Fiddling with DNS entries via some APIs if you want to setup them automatically is pretty messy. Additionally you might know how long it takes for a new DNS entry to be visible on all DNS servers (up to 24 hours). So a SMTP like service that's already fully available and where you have full programmatically control over it would make some things way easier.

**Comment by lane-c-wagner** [comment]
@shilch What if we specified an endpoint for forwarding requests to a specified server so we don't need to use DNS entries?

**Comment by lane-c-wagner** [comment]
OR if I own lane.com but my ccap provider is ogdolo.com, when a wallet hits the GET https://lane.com/ccap/address/lane/nano instead of getting back my address and a 200 response, they get a redirect of some sort?

**Comment by shilch** [comment]
@FrilledShark Now I get what you mean. When linking to an external server, the TLS certificate does not confirm ownership of your domain. However, as you said, this is a very niche attack and SMTP is vulnerable to this as well.

@BitDesert Yep, an SMTP like service is much more flexible and can update very quickly. Also, it allows some cool stuff like asking the owner of the alias to generate a new address in case he's online (like Handcash does).

@lane-c-wagner You might own a domain but not a server.

**Comment by FrilledShark** [comment]
@lane-c-wagner It would be easier going @BitDesert's idea and using subdomains. If you wanted to use ogdoolo.com as your provider, you forward ccap.lane.com to ccap.ogdoolo.com and it would handle it.

@shilch Yes. It is, but if evil guy could earn a few bucks, you be sure he tries as hard to.

**Comment by shilch** [comment]
@FrilledShark How is forwarding the subdomains any different to SRV? There is still no certificate that proofs ownership...

**Comment by shilch** [comment]
An evil attacker could still rewrite to forward to an own domain which he has a certificate for. No difference to SRV

**Comment by FrilledShark** [comment]
ogdoolo.com can create a valid certificate for the subdomain.

**Comment by BitDesert** [comment]
You don't need any redirects with this solution.
So the wallet would query `_ccap._tcp.ogdolo.com` and ask for the IP address of the CCAP server. It gets back a domain name like `ccap.nano.org` which is an A record with the final server which it connects to. Then it connects via HTTPS to the endpoint and asks for the alias.

To that certificate problem: It has to be a valid HTTPS certificate for that domain, but if we can't trust it the whole certificate system we're currently using would be broken.

**Comment by lane-c-wagner** [comment]
@BitDesert what kind of query is being made to _ccap._tcp.ogdolo.com?

**Comment by shilch** [comment]
@lane-c-wagner SRV, as written in this PR.

**Comment by FrilledShark** [comment]
@BitDesert With that, you will just be overlaying the nano.org ccap server with the custom domain name, which would be a little disappointing.

**Comment by BitDesert** [comment]
@FrilledShark Yean mean why we use another A record for the CCAP server and not directly an IP?

**Comment by FrilledShark** [comment]
@shilch I got it working. If you don't trust me, point your subdomain towards 51.15.195.182 and I will show you an error page on a 2 dollar vps with a valid let's encrypt certificate.

To showcase:
ccap.nanoalias.io is hosted separate to nanoalias.io (main domain). Both have valid certificates.

**Comment by FrilledShark** [comment]
@bitdesert I will try to setup my third party ccap server tomorrow and show you what I mean.

**Comment by shilch** [comment]
@FrilledShark Yeah, but if I want to use your server as a 3rd party to host my ccap domain then you need to handle multiple certificates. Also, if a client establishes a connection to your server, your server does not know which domain I'm going to request before starting the encryption.

**Comment by lane-c-wagner** [comment]
I made a server just to discuss CCAP stuff: https://discord.gg/A8Jkp2

**Comment by FrilledShark** [comment]
@shilch if the server uses and browser support [SNI](http://nginx.org/en/docs/http/configuring_https_servers.html#sni) it is not a problem.

**Comment by lane-c-wagner** [comment]
@shilch We need to update this PR to reflect that the TXT record is optional and how if used it is simply to point all requests to the HOST (3rd party) domain

**Pull request closed without merging**
